import { Router } from 'express';
import multer from 'multer';
import { authenticate, requirePermission } from '../auth.js';
import { config } from '../config.js';
import { execute, one, rows, transaction } from '../db.js';
import { asyncHandler, HttpError, ok, created } from '../http.js';
import type { AuthRequest } from '../types.js';

const upload = multer({ dest: config.uploadDir, limits: { fileSize: config.maxUploadBytes } });
export const dailyControlRouter = Router();
const canViewAll = (user: Record<string, unknown>) => Number(user.daily_control_all ?? 0) === 1 || String(user.username).toUpperCase() === 'SUPERUSER';

dailyControlRouter.get('/daily-control', authenticate, requirePermission('daily_control', 'daily_control_all'), asyncHandler(async (req, res) => {
  const user = (req as AuthRequest).user!; const limit = Math.min(Number(req.query.limit ?? 50), 200); const params: unknown[] = []; let where = 'WHERE 1=1';
  if (!canViewAll(user)) { where += ' AND dc.id_division=?'; params.push(user.id_division); }
  if (req.query.date) { where += ' AND dc.activity_date=?'; params.push(req.query.date); }
  const data = await rows(`SELECT dc.*, COUNT(DISTINCT m.id) AS media_count, COUNT(DISTINCT c.id) AS comment_count FROM tb_daily_control dc LEFT JOIN tb_daily_control_media m ON m.daily_control_id=dc.id LEFT JOIN tb_daily_control_comment c ON c.daily_control_id=dc.id ${where} GROUP BY dc.id ORDER BY dc.activity_date DESC, dc.activity_time DESC, dc.id DESC LIMIT ?`, [...params, limit]); ok(res, data);
}));
dailyControlRouter.get('/daily-control/summary', authenticate, requirePermission('daily_control', 'daily_control_all'), asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const where = canViewAll(user) ? '' : 'WHERE id_division=?'; const params = canViewAll(user) ? [] : [user.id_division]; const data = await rows(`SELECT status, COUNT(*) total FROM tb_daily_control ${where} GROUP BY status`, params); ok(res, { statuses: data }); }));
dailyControlRouter.get('/daily-control/activities', authenticate, requirePermission('daily_control', 'daily_control_all'), asyncHandler(async (req, res) => { const id = req.query.id; if (!id) throw new HttpError(400, 'id is required'); const activity = await one('SELECT * FROM tb_daily_control WHERE id=?', [id]); if (!activity) throw new HttpError(404, 'Activity not found'); const [media, tags, comments, followups] = await Promise.all([rows('SELECT * FROM tb_daily_control_media WHERE daily_control_id=?', [id]), rows('SELECT * FROM tb_daily_control_tag WHERE daily_control_id=?', [id]), rows('SELECT * FROM tb_daily_control_comment WHERE daily_control_id=? ORDER BY created_at', [id]), rows('SELECT * FROM tb_daily_control_followup WHERE daily_control_id=?', [id])]); ok(res, { ...activity as object, media, tags, comments, followups }); }));
dailyControlRouter.post('/daily-control/activity', authenticate, requirePermission('daily_control'), upload.array('media', 10), asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const b = req.body; if (!b.title) throw new HttpError(400, 'title is required'); const id = await transaction(async (connection) => { const [result] = await connection.execute<import('mysql2/promise').ResultSetHeader>('INSERT INTO tb_daily_control (activity_date,activity_time,id_company,id_division,id_user,fullname,AssetCode,part_mesin,wo_number,title,notes,status,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [b.activity_date ?? new Date().toISOString().slice(0,10), b.activity_time ?? null, user.id_company, user.id_division, user.id_user, user.fullname, b.AssetCode ?? null, b.part_mesin ?? null, b.wo_number ?? null, b.title, b.notes ?? null, b.status ?? 'POSTED', user.fullname, user.fullname]); for (const file of (req.files as Express.Multer.File[] ?? [])) await connection.execute('INSERT INTO tb_daily_control_media (daily_control_id,media_type,media_name,media_path,file_size,mime_type,created_by) VALUES (?,?,?,?,?,?,?)', [result.insertId, file.mimetype.startsWith('video/') ? 'video' : 'image', file.originalname, file.path.replaceAll('\\','/'), file.size, file.mimetype, user.fullname]); return result.insertId; }); created(res, { id }, 'Daily Control activity created'); }));
dailyControlRouter.get('/daily-control/comments', authenticate, asyncHandler(async (req, res) => { const id = req.query.daily_control_id ?? req.query.id; if (!id) throw new HttpError(400, 'daily_control_id is required'); ok(res, await rows('SELECT * FROM tb_daily_control_comment WHERE daily_control_id=? ORDER BY created_at', [id])); }));
dailyControlRouter.post('/daily-control/comment', authenticate, asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const { daily_control_id, message, parent_id = null } = req.body; if (!daily_control_id || !message) throw new HttpError(400, 'daily_control_id and message are required'); const result = await execute('INSERT INTO tb_daily_control_comment (daily_control_id,parent_id,id_user,fullname,division_name,message,created_at) VALUES (?,?,?,?,?,?,NOW())', [daily_control_id,parent_id,user.id_user,user.fullname,user.division_name ?? null,message]); created(res, { id: result.insertId }, 'Comment added'); }));
dailyControlRouter.get('/daily-control/unread', authenticate, asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const item = await one<{ total: number }>('SELECT COUNT(*) total FROM tb_daily_control dc LEFT JOIN tb_daily_control_read r ON r.daily_control_id=dc.id AND r.id_user=? WHERE r.id IS NULL AND dc.id_user<>?', [user.id_user,user.id_user]); ok(res, { unread: Number(item?.total ?? 0) }); }));
dailyControlRouter.post('/daily-control/read', authenticate, asyncHandler(async (req, res) => { const id = req.body.daily_control_id ?? req.body.id; if (!id) throw new HttpError(400, 'daily_control_id is required'); await execute('INSERT INTO tb_daily_control_read (daily_control_id,id_user,last_read_at) VALUES (?,?,NOW()) ON DUPLICATE KEY UPDATE last_read_at=NOW()', [id,(req as AuthRequest).user!.id_user]); ok(res, null, 'Marked as read'); }));
dailyControlRouter.get('/daily-control/mention-users', authenticate, asyncHandler(async (req, res) => { const q = String(req.query.q ?? ''); ok(res, await rows('SELECT id_user,fullname,username,avatar FROM tb_user WHERE active=1 AND (fullname LIKE ? OR username LIKE ?) ORDER BY fullname LIMIT 30', [`%${q}%`,`%${q}%`])); }));
dailyControlRouter.get('/daily-control/part-mentions', authenticate, asyncHandler(async (req, res) => { const q = String(req.query.q ?? ''); ok(res, await rows('SELECT id,AssetCode,part,uom,qty_on_hand FROM tb_parts_bom WHERE is_active=1 AND part LIKE ? ORDER BY part LIMIT 50', [`%${q}%`])); }));
