import { Router } from 'express';
import { authenticate, requirePermission } from '../auth.js';
import { execute, one, rows, transaction } from '../db.js';
import { asyncHandler, HttpError, ok, created } from '../http.js';
import type { AuthRequest } from '../types.js';

export const materialRouter = Router();
materialRouter.get('/material-usage/list', authenticate, asyncHandler(async (req, res) => { const status = req.query.status ? 'WHERE status=?' : ''; ok(res, await rows(`SELECT * FROM tb_material_part_request ${status} ORDER BY created_at DESC LIMIT ?`, req.query.status ? [req.query.status,100] : [100])); }));
materialRouter.get('/material-usage/detail', authenticate, asyncHandler(async (req, res) => { const id = req.query.id; if (!id) throw new HttpError(400, 'id is required'); const item = await one('SELECT * FROM tb_material_part_request WHERE id=?', [id]); if (!item) throw new HttpError(404, 'Material request not found'); ok(res, item); }));
materialRouter.post('/material-usage/request', authenticate, asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const b = req.body; const requests = Array.isArray(b.requests) ? b.requests : Array.isArray(b.materials) ? b.materials : [b]; if (!b.wo_number || !requests.length) throw new HttpError(400, 'wo_number and material requests are required'); const ids = await transaction(async (connection) => { const result: number[] = []; for (const r of requests) { const [insert] = await connection.execute<import('mysql2/promise').ResultSetHeader>('INSERT INTO tb_material_part_request (wo_number,job_executor,requested_by,requested_by_name,request_note,status,part_name,qty,uom,created_at,updated_at) VALUES (?,?,?,?,?,"PENDING",?,?,?,NOW(),NOW())', [b.wo_number,b.job_executor ?? null,user.id_user,user.fullname,r.note ?? b.request_note ?? null,r.part_name ?? r.part ?? null,r.qty ?? null,r.uom ?? null]); result.push(insert.insertId); } return result; }); created(res, { ids }, 'Material request submitted'); }));
materialRouter.post('/material-usage/select-parts', authenticate, requirePermission('material_usage'), asyncHandler(async (req, res) => { const user = (req as AuthRequest).user!; const { id, part_name, qty, uom, pr_number } = req.body; if (!id || !part_name || !qty) throw new HttpError(400, 'id, part_name and qty are required'); await execute('UPDATE tb_material_part_request SET status="SELECTED",part_name=?,qty=?,uom=?,pr_number=?,selected_by=?,selected_by_name=?,selected_at=NOW(),updated_at=NOW() WHERE id=? AND status="PENDING"', [part_name,qty,uom ?? 'PCS',pr_number ?? null,user.id_user,user.fullname,id]); ok(res, { id, status: 'SELECTED' }, 'Part selected'); }));
materialRouter.post('/material-usage/set-usage', authenticate, requirePermission('material_usage'), asyncHandler(async (req, res) => { const { part_id, qty, note = null } = req.body; if (!part_id || !qty || Number(qty) <= 0) throw new HttpError(400, 'part_id and a positive qty are required'); await transaction(async (connection) => { await connection.execute('UPDATE tb_parts_bom SET qty_on_hand=qty_on_hand-?, total_used=COALESCE(total_used,0)+?,last_usage_date=CURDATE(),updated_at=NOW() WHERE id=? AND qty_on_hand>=?', [qty,qty,part_id,qty]); await connection.execute('INSERT INTO tb_parts_usage_history (part_id,qty,note,created_at) VALUES (?,?,?,NOW())', [part_id,qty,note]); }); ok(res, null, 'Part usage recorded'); }));
materialRouter.post('/material-usage/restock', authenticate, requirePermission('material_usage'), asyncHandler(async (req, res) => { const { part_id, qty } = req.body; if (!part_id || !qty || Number(qty) <= 0) throw new HttpError(400, 'part_id and a positive qty are required'); await execute('UPDATE tb_parts_bom SET qty_on_hand=qty_on_hand+?,updated_at=NOW() WHERE id=?', [qty,part_id]); ok(res, null, 'Part restocked'); }));
materialRouter.post('/material-usage/hold', authenticate, asyncHandler(async (req, res) => { const { id } = req.body; if (!id) throw new HttpError(400, 'id is required'); await execute('UPDATE tb_material_part_request SET status="PENDING",updated_at=NOW() WHERE id=?', [id]); ok(res, { id }, 'Request held'); }));
materialRouter.post('/material-usage/confirm', authenticate, requirePermission('material_usage'), asyncHandler(async (req, res) => { const { id } = req.body; if (!id) throw new HttpError(400, 'id is required'); await execute('UPDATE tb_material_part_request SET status="FULFILLED",erp_status="CONFIRMED",updated_at=NOW() WHERE id=? AND status IN ("SELECTED","SENT_ERP")', [id]); ok(res, { id, status: 'FULFILLED' }, 'Material confirmed'); }));
materialRouter.delete('/material-usage/cancel', authenticate, asyncHandler(async (req, res) => { const id = req.body.id ?? req.query.id; if (!id) throw new HttpError(400, 'id is required'); await execute('UPDATE tb_material_part_request SET status="CANCELLED",updated_at=NOW() WHERE id=? AND status="PENDING"', [id]); ok(res, { id }, 'Request cancelled'); }));
materialRouter.get('/material-usage/erp-parts', authenticate, asyncHandler(async (req, res) => { const q = String(req.query.q ?? ''); ok(res, await rows('SELECT id,AssetCode,part,uom,qty_on_hand,company FROM tb_parts_bom WHERE is_active=1 AND part LIKE ? ORDER BY part LIMIT 100', [`%${q}%`])); }));
materialRouter.post('/material-usage/trigger_erp', authenticate, requirePermission('material_usage'), asyncHandler(async (req, res) => { const { id } = req.body; if (!id) throw new HttpError(400, 'id is required'); await execute('UPDATE tb_material_part_request SET status="SENT_ERP",erp_status="SENT",erp_sent_at=NOW(),updated_at=NOW() WHERE id=? AND status="SELECTED"', [id]); ok(res, { id, status: 'SENT_ERP' }, 'ERP dispatch recorded'); }));
