import { Router } from 'express';
import type { PoolConnection } from 'mysql2/promise';
import { authenticate, requirePermission } from '../auth.js';
import { execute, one, rows, transaction } from '../db.js';
import { asyncHandler, HttpError, ok, created } from '../http.js';
import type { AuthRequest, User } from '../types.js';

export const workOrderRouter = Router();
type Domain = 'is' | 'ga' | 'meso' | 'maintenance' | 'production';
const domains: Record<Domain, { table: string; approval: string; prefix: string; permission: string; executor: string }> = {
  is: { table: 'tb_wo_it', approval: 'tb_approval_it', prefix: 'WOIT', permission: 'wo_it', executor: 'ITS' },
  ga: { table: 'tb_wo_ga', approval: 'tb_approval_ga', prefix: 'WOGA', permission: 'wo_ga', executor: 'HRGA' },
  meso: { table: 'tb_wo_mtc', approval: 'tb_approval', prefix: 'WO', permission: 'wo_mtc', executor: 'MESO' },
  maintenance: { table: 'tb_wo_mtc_operational', approval: 'tb_approval_operational', prefix: 'WOPR', permission: 'wo_operational', executor: 'MTC' },
  production: { table: 'tb_wo_production', approval: 'tb_approval', prefix: 'WOPD', permission: 'wo_it', executor: 'PRODUCTION' },
};
const domainOf = (value: string): Domain => { if (!(value in domains)) throw new HttpError(404, 'Unknown work order domain'); return value as Domain; };
const terminal = new Set(['CLOSED', 'VOID', 'REJECT', 'DECLINE']);
const permissive = (user: User, permission: string): boolean => String(user.username).toUpperCase() === 'SUPERUSER' || Number(user[permission] ?? 0) === 1 || Number(user.wo_cross_access ?? 0) === 1;

async function nextNumber(connection: PoolConnection, domain: Domain, division: string): Promise<string> {
  const d = domains[domain]; const date = new Date(); const month = String(date.getMonth() + 1).padStart(2, '0'); const year = date.getFullYear(); const base = `${d.prefix}-${month}${year}/${division}`;
  const [query] = await connection.query('SELECT MAX(CAST(RIGHT(wo_number,4) AS UNSIGNED)) AS seq FROM ?? WHERE wo_number LIKE ?', [d.table, `${base}/%`]);
  const sequence = (query as Array<{ seq: number | null }>)[0]?.seq ?? 0;
  return `${base}/${String(Number(sequence) + 1).padStart(4, '0')}`;
}
async function header(domain: Domain, wo: string) { const d = domains[domain]; return one(`SELECT w.*, a.AssetCode, a.AssetName, d.division_name, d.division_code FROM \`${d.table}\` w LEFT JOIN asset a ON a.AssetID=w.id_equipment LEFT JOIN tb_division d ON d.id_division=w.id_division WHERE w.wo_number=?`, [wo]); }
async function approval(connection: PoolConnection, table: string, wo: string, user: User, comment: string) { await connection.execute(`INSERT INTO \`${table}\` (wo_number,fullname,avatar,id_division,id_position,comment,created_at) VALUES (?,?,?,?,?,?,NOW())`, [wo, user.fullname, user.avatar ?? 'avatar.png', user.id_division, user.id_position, comment]); }

workOrderRouter.get('/work-orders/options', authenticate, asyncHandler(async (_req, res) => {
  const [types, priorities, shifts, assets] = await Promise.all([rows('SELECT DISTINCT type_wo AS value FROM tb_wo_mtc_operational WHERE type_wo IS NOT NULL'), rows('SELECT DISTINCT priority AS value FROM tb_wo_mtc_operational WHERE priority IS NOT NULL'), rows('SELECT DISTINCT shift AS value FROM tb_wo_mtc_operational WHERE shift IS NOT NULL'), rows('SELECT AssetID,AssetCode,AssetName FROM asset WHERE active="active" ORDER BY AssetName LIMIT 500')]); ok(res, { types, priorities, shifts, assets });
}));
workOrderRouter.get('/work-orders', authenticate, asyncHandler(async (req, res) => {
  const domain = String(req.query.domain ?? 'maintenance'); const selected = domain === 'all' ? Object.keys(domains) as Domain[] : [domainOf(domain)]; const user = (req as AuthRequest).user!; const q = String(req.query.q ?? ''); const limit = Math.min(200, Math.max(1, Number(req.query.limit ?? 50)));
  const result = await Promise.all(selected.filter((key) => permissive(user, domains[key].permission)).map((key) => rows(`SELECT '${key}' AS domain, wo_number,date,type_wo,priority,id_division,id_equipment,job_title,status,pic,job_executor,creator,created_at,updated_at FROM \`${domains[key].table}\` WHERE wo_number LIKE ? OR job_title LIKE ? ORDER BY created_at DESC LIMIT ?`, [`%${q}%`, `%${q}%`, limit])));
  ok(res, result.flat().sort((a, b) => String(b.created_at).localeCompare(String(a.created_at))).slice(0, limit));
}));
workOrderRouter.get('/work-orders/detail', authenticate, asyncHandler(async (req, res) => {
  const domain = domainOf(String(req.query.domain ?? 'maintenance')); const wo = String(req.query.wo_number ?? ''); if (!wo) throw new HttpError(400, 'wo_number is required'); const d = domains[domain]; const item = await header(domain, wo); if (!item) throw new HttpError(404, 'Work order not found');
  const [executors, labor, materials, approvals, evidence] = await Promise.all([rows('SELECT * FROM tb_job_executor WHERE wo_number=? ORDER BY id', [wo]), rows('SELECT * FROM tb_detail_labor WHERE wo_number=? ORDER BY id', [wo]), rows('SELECT * FROM tb_detail_material WHERE wo_number=? ORDER BY id', [wo]), rows(`SELECT * FROM \`${d.approval}\` WHERE wo_number=? ORDER BY created_at`, [wo]), rows('SELECT * FROM tb_wo_service_evidence WHERE wo_number=? ORDER BY created_at', [wo])]); ok(res, { ...item as object, domain, executors, labor, materials, approvals, evidence });
}));

workOrderRouter.post('/work-orders/create', authenticate, asyncHandler(async (req, res) => {
  const domain = domainOf(String(req.body.domain ?? 'maintenance')); const d = domains[domain]; const user = (req as AuthRequest).user!; if (!permissive(user, d.permission)) throw new HttpError(403, 'You do not have permission to create this work order');
  const b = req.body; if (!b.job_title) throw new HttpError(400, 'job_title is required'); const isPreventive = /preventive/i.test(String(b.type_wo ?? '')); const wo = await transaction(async (connection) => { const number = b.wo_number ?? await nextNumber(connection, domain, String(user.division_code ?? user.id_division)); const status = domain === 'maintenance' && isPreventive ? 'IN_PROGRESS_EXECUTOR' : (b.status ?? 'WAIT_KA_DIV'); const values = [number, b.date ?? new Date().toISOString().slice(0, 10), b.company ?? user.company_name ?? '', b.shift ?? '', b.type_wo ?? 'CORRECTIVE', b.priority ?? 'NORMAL', b.id_division ?? user.id_division, b.id_equipment ?? null, b.job_title, b.running_hours ?? null, b.job_requirement ?? '', d.executor, status, d.executor, user.fullname]; await connection.execute(`INSERT INTO \`${d.table}\` (wo_number,date,company,shift,type_wo,priority,id_division,id_equipment,job_title,running_hours,job_requirement,job_executor,status,pic,creator,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())`, values); await connection.execute('INSERT INTO tb_job_executor (job_executor,wo_number,status,created_at) VALUES (?,?,?,NOW())', [d.executor, number, isPreventive ? 'IN_PROGRESS' : 'WAITING']); return number; }); created(res, { wo_number: wo, domain }, 'Work order created');
}));
workOrderRouter.post('/work-orders/update', authenticate, asyncHandler(async (req, res) => { const domain = domainOf(String(req.body.domain ?? 'maintenance')); const d = domains[domain]; const wo = String(req.body.wo_number ?? ''); if (!wo) throw new HttpError(400, 'wo_number is required'); const item = await header(domain, wo) as Record<string, unknown> | null; if (!item) throw new HttpError(404, 'Work order not found'); if (terminal.has(String(item.status).toUpperCase())) throw new HttpError(409, 'Terminal work order cannot be edited'); const fields = ['date','company','shift','type_wo','priority','id_division','id_equipment','job_title','running_hours','job_requirement','attachment'].filter((key) => req.body[key] !== undefined); if (!fields.length) throw new HttpError(400, 'No changes provided'); await execute(`UPDATE \`${d.table}\` SET ${fields.map((key) => `\`${key}\`=?`).join(', ')}, updated_at=NOW() WHERE wo_number=?`, [...fields.map((key) => req.body[key]), wo]); ok(res, { wo_number: wo }, 'Work order updated'); }));

workOrderRouter.post('/work-orders/approve', authenticate, asyncHandler(async (req, res) => transition(req as AuthRequest, res, 'approve')));
workOrderRouter.post('/work-orders/reject', authenticate, asyncHandler(async (req, res) => transition(req as AuthRequest, res, 'reject')));
workOrderRouter.post('/work-orders/close', authenticate, asyncHandler(async (req, res) => transition(req as AuthRequest, res, 'close')));
workOrderRouter.post('/work-orders/void', authenticate, asyncHandler(async (req, res) => transition(req as AuthRequest, res, 'void')));
async function transition(req: AuthRequest, res: import('express').Response, action: 'approve'|'reject'|'close'|'void'): Promise<void> { const domain = domainOf(String(req.body.domain ?? 'maintenance')); const d = domains[domain]; const wo = String(req.body.wo_number ?? ''); const comment = String(req.body.comment ?? req.body.reason ?? ''); if (!wo) throw new HttpError(400, 'wo_number is required'); const item = await header(domain, wo) as Record<string, unknown> | null; if (!item) throw new HttpError(404, 'Work order not found'); if (terminal.has(String(item.status).toUpperCase())) throw new HttpError(409, 'Work order is already terminal'); const target = action === 'approve' ? 'IN_PROGRESS_EXECUTOR' : action === 'reject' ? 'REJECT' : action === 'close' ? 'CLOSED' : 'VOID'; await transaction(async (connection) => { await approval(connection, d.approval, wo, req.user!, comment); await connection.execute(`UPDATE \`${d.table}\` SET status=?, pic=?, updated_at=NOW()${action === 'close' ? ', closedDate=NOW()' : ''}${action === 'void' ? ', reason=?' : ''} WHERE wo_number=?`, action === 'void' ? [target, '-', comment, wo] : [target, action === 'approve' ? d.executor : '-', wo]); }); ok(res, { wo_number: wo, status: target }, `Work order ${action}d`); }

workOrderRouter.post('/work-orders/planner', authenticate, asyncHandler(async (req, res) => { const domain = domainOf(String(req.body.domain ?? 'maintenance')); const wo = String(req.body.wo_number ?? ''); if (!wo) throw new HttpError(400, 'wo_number is required'); const executors = Array.isArray(req.body.executors) ? req.body.executors : []; await transaction(async (connection) => { if (executors.length) { await connection.execute('DELETE FROM tb_job_executor WHERE wo_number=?', [wo]); for (const executor of executors) await connection.execute('INSERT INTO tb_job_executor (wo_number,job_executor,status,created_at) VALUES (?,?,?,NOW())', [wo, executor.job_executor ?? executor, 'IN_PROGRESS']); } await connection.execute(`UPDATE \`${domains[domain].table}\` SET status='IN_PROGRESS_EXECUTOR', updated_at=NOW() WHERE wo_number=?`, [wo]); }); ok(res, { wo_number: wo, executor_count: executors.length }, 'Planner assignment saved'); }));
workOrderRouter.post('/work-orders/sub', authenticate, asyncHandler(async (req, res) => { const source = domainOf(String(req.body.domain ?? 'maintenance')); const target = domainOf(String(req.body.target_domain ?? req.body.subto ?? '')); const original = await header(source, String(req.body.wo_number ?? '')) as Record<string, unknown> | null; if (!original) throw new HttpError(404, 'Source work order not found'); const user = (req as AuthRequest).user!; const d = domains[target]; const number = await transaction(async (connection) => { const n = await nextNumber(connection, target, String(user.division_code ?? user.id_division)); await connection.execute(`INSERT INTO \`${d.table}\` (wo_number,date,company,shift,type_wo,priority,id_division,id_equipment,job_title,running_hours,job_requirement,job_executor,status,pic,creator,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())`, [n, new Date().toISOString().slice(0,10), original.company ?? '', original.shift ?? '', original.type_wo ?? 'CORRECTIVE', original.priority ?? 'NORMAL', original.id_division, original.id_equipment, original.job_title, original.running_hours ?? null, original.job_requirement ?? '', d.executor, 'WAIT_KA_DIV', d.executor, user.fullname] as never); return n; }); created(res, { sub_wo_number: number, domain: target }, 'Sub work order created'); }));

workOrderRouter.get('/work-orders/assets', authenticate, asyncHandler(async (req, res) => ok(res, await rows('SELECT AssetID,AssetCode,AssetName,CompanyName,LocationAsset,mtc_area_key FROM asset WHERE active="active" AND (AssetCode LIKE ? OR AssetName LIKE ?) ORDER BY AssetName LIMIT 100', [`%${String(req.query.q ?? '')}%`, `%${String(req.query.q ?? '')}%`]))));
workOrderRouter.get('/work-orders/materials', authenticate, asyncHandler(async (req, res) => { const wo = String(req.query.wo_number ?? ''); if (!wo) throw new HttpError(400, 'wo_number is required'); ok(res, await rows('SELECT * FROM tb_detail_material WHERE wo_number=? ORDER BY id', [wo])); }));
